import React from 'react';

function TermsOfService() {
  return (
    <div className="max-w-4xl mx-auto py-8 px-4">
      <h1 className="text-3xl font-bold mb-4">Terms of Service</h1>
      <p>
        This is the Terms of Service page. Here we outline the rules and regulations for using our service.
      </p>
      <p>
        By using our service, you agree to comply with these terms. Please read them carefully.
      </p>
      <h2 className="text-2xl font-semibold mt-6 mb-3">📌 Project Nature</h2>
      <p className="mb-6">
        This service is provided as a side project developed during the creators' personal time, with no intention or prospect of generating revenue.
      </p>
      <h2 className="text-2xl font-semibold mb-3">🔑 User Responsibility</h2>
      <p className="mb-6">
        Users are required to use their own OpenAI API key to access the service. The service utilizes Cloudflare Workers to handle HTTP status code verification for YouTube recommendations.
      </p>
      <h2 className="text-2xl font-semibold mb-3">🤖 Technology Used</h2>
      <p className="mb-6">
        The service does not employ the official YouTube API; instead, all recommendations are generated through Generative AI technology (specifically GPT-4.1-nano).
      </p>
      <h2 className="text-2xl font-semibold mb-3">⚠️ Liability Disclaimer</h2>
      <p className="mb-6">
        By using this service, you acknowledge and agree that the creators and providers of this service bear no responsibility or liability for any issues, claims, or damages arising from commercial use or any other use of the recommendations or content generated by the service. The service is provided "as is" without warranties of any kind, either express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, or non-infringement.
      </p>
      <h2 className="text-2xl font-semibold mb-3">📜 Legal Compliance and Indemnity</h2>
      <p>
        Users are solely responsible for ensuring that their use of the service complies with all applicable laws, regulations, and third-party rights. By continuing to use the service, you agree to indemnify and hold harmless the creators from any claims, damages, losses, liabilities, costs, or expenses arising from your use of the service.
      </p>
    </div>
  );
}

export default TermsOfService;
