# -*- coding: utf-8 -*-
"""extract subs from html.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_T_kwCu0n6CLqwNA7n90lsX2yFNGLR0e
"""

from bs4 import BeautifulSoup

# Load HTML content from the file
with open("/content/YouTube.html", "r", encoding="utf-8") as f:
    html = f.read()

# Parse with BeautifulSoup
soup = BeautifulSoup(html, 'html.parser')

# Extract all channel renderers
channels = soup.select('ytd-channel-renderer')

# For each channel, extract name and handle
results = []
for ch in channels:
    # Channel name
    name_tag = ch.select_one('ytd-channel-name yt-formatted-string#text')
    name = name_tag.text.strip() if name_tag else None

    # Channel handle (href containing "/@")
    handle_tag = ch.select_one('a.channel-link[href*="/@"]')
    handle = handle_tag['href'].strip() if handle_tag else None
    handle_url = f"https://www.youtube.com{handle}" if handle else None

    if name and handle_url:
        results.append((name, handle_url))

# Display results
for name, url in results:
    print(f"Channel Name: {name}")
    print(f"Channel URL: {url}")
    print("---")

len(results)

